### ISSUE TITLE
Pozicija EUR cijene

### ISSUE THREAD

**Issue by budimir80** [croz-ltd/hrk2eur#4]
Prema najnovijim smjernicama EUR cijena mora biti iskazana iznad KN cijene ili s lijeve strane KN cijene. Ovo bi trebao biti format prikaza cijene:

100 EUR (753,00 Kn) 
ili
100EUR
(753,00 Kn)

Bilo bi dobro prepraviti trenutni prikaz kako se ne bi stvorio problem korisnicima ove vrlo korisne skripte! Thumbs up za odrađeni posao.

**Comment by jtomic-croz** [comment]
Pozdrav, dodali smo zastavicu `isEurPrimary` u verziji 1.2.0 s kojom se moze upravljati koja se vrijednost stavlja na prvo mjesto. Trenutno je defaultno na false, jer smo primjetili da vecina firmi ima implementirano kune kao primarne.
Ukoliko na vasoj stranici zelite postaviti eure kao primarne, samo umjesto 
`watchPrices()` pozovite `watchPrices({ isEurPrimary: true })`

**Comment by mark12cro** [comment]
Pozdrav,

zamjenio sam CDN skriptu 2 za skriptu 1, kada je bila skripta 1. Prije je normalno radilo a kada sam umetnuo watchPrices({ isEurPrimary: true }) i verzija 1.1.2  više ne radi.. blokira stranica.  Možete staviti koja je Cdn skripta da bude ispravno prikazano da je primarna valuta euro, to će biti obavezno od 05.09.2022.
Hvala,

1)
<script src="https://unpkg.com/@croz/hrk2eur@1.1.0/dist/umd/main.js"></script>
<script>hrk2eur.watchPrices()</script>

2)
<script src="https://unpkg.com/@croz/hrk2eur@1.2.0/dist/umd/main.js"></script>
<script>hrk2eur.watchPrices({ isEurPrimary: true })</script>
