### ISSUE TITLE
CDN skripta  EUR/Kn

### ISSUE THREAD

**Issue by mark12cro** [croz-ltd/hrk2eur#5]
Pozdrav,

isprika na smetnji znam da imate puno posla, nisam znao kako drukčije da Vas kontaktiram..

Molim Vas koju CDN skriptu da stavim umjesto ove skripte da se prikazuje na primarnoj poziciji prvo euro.
<script src="https://unpkg.com/@croz/hrk2eur@1.1.0/dist/umd/main.js"></script> <script>hrk2eur.watchPrices()</script>

"
zamjenio sam CDN skriptu 2 za skriptu 1, kada je bila skripta 1. Prije je normalno radilo a kada sam umetnuo watchPrices({ isEurPrimary: true }) i verzija 1.2.0više ne radi.. blokira stranica. Možete staviti koja je Cdn skripta da bude ispravno prikazano da je primarna valuta euro, to će biti obavezno od 05.09.2022.
Hvala,

<script src="https://unpkg.com/@croz/hrk2eur@1.1.0/dist/umd/main.js"></script> <script>hrk2eur.watchPrices()</script>

<script src="https://unpkg.com/@croz/hrk2eur@1.2.0/dist/umd/main.js"></script> <script>hrk2eur.watchPrices({ isEurPrimary: true })</script> 
"
Hvala i lijep pozdrav,

**Comment by jtomic-croz** [comment]
Pozdrav @mark12cro .

Tocno koristenje bi trebalo biti sa:
```
<script src="https://unpkg.com/@croz/hrk2eur@1.2.0/dist/umd/main.js"></script>
<script>hrk2eur.watchPrices({ isEurPrimary: true })</script>
```

sto cemo i dodati u README.
Kazete da vam taj pristup ne radi?

**Comment by mark12cro** [comment]
Pozdrav,

ne radi mi taj pristup, kada stavim tu skriptu stranica se ne učitava pravilno, jako sporo ne može se učitati,

kod stare kada je prvo Kn radi super

**Comment by jtomic-croz** [comment]
Okej. budemo provjerili u cemu je problem

**Comment by mark12cro** [comment]
Može, puno hvala...   sad probao ponovo stranica se ne može cijela učitati...

**Comment by jtomic-croz** [comment]
Mozete probati sad sa ovime?

```
<script src="https://unpkg.com/@croz/hrk2eur@1.2.1/dist/umd/main.js"></script>
<script>hrk2eur.watchPrices({ isEurPrimary: true })</script>

**Comment by mark12cro** [comment]
Radi, svaka Vam čast :)

**Comment by jtomic-croz** [comment]
Super, zatvaram onda issue :)

**Comment by mark12cro** [comment]
Hvala Vam puno ! kad ću trebat usluge koje nudite prvi ste na spisku :)
