### ISSUE TITLE
Nova CDN skripta prikazuje se samo EUR

### ISSUE THREAD

**Issue by mark12cro** [croz-ltd/hrk2eur#7]
Poštovanje, probao sam testirati CDN skriptu koja će se koristiti od 01.01.2023. .. Prebacio sam glavnu valuta shopa na EUR, umetnuo novu skriptu kjoja se koristi od 01.01.2023.  umjesto stare skriptu te se prikazuje samo EUR.  Ne prikazuje dvojni prikaz EUR i HRK...

<script src="https://unpkg.com/@croz/hrk2eur@1.3.1/dist/umd/main.js"></script>
<script>hrk2eur.watchPrices({ autoSwitchOnEurIntroduction: true })</script>

Molim Vas ako možete provjeriti,
Hvala puno i lijep pozdrav,
Saša

**Comment by jtomic-croz** [comment]
Ako testirate prije 1.1.2023., trebate umjesto `autoSwitchOnEurIntroduction` koristiti zastavicu `convertEurToHrk`.

`autoSwitchOnEurIntroduction` funkcionira tako da ceka 01.01.2023 i nakon tog prebacuje racunicu sa HRK -> EUR na EUR -> HRK, te da se moze koristiti i prije i poslije konverzije (uzimajuci u obzir da ostatak sustava mora vracati nove cijene).

**Comment by jtomic-croz** [comment]
Zbog manjka aktivnosti zatvoriti cu issue. Ukoliko vam se problem jos uvijek događa, slobodno ga reopenajte :)

**Comment by mark12cro** [comment]
Poštovanje, puno hvala. Sve super radi svaka čast :)
