### ISSUE TITLE
Pogrešna konverzija za format €3.500,00 EUR

### ISSUE THREAD

**Issue by mblataric** [croz-ltd/hrk2eur#8]
Pozdrav, 

pokrenuo sam Shopify online shop i u zadnji tren shvatio da treba riješit dvojno iskazivanje cijena :-( 

Našao sam Vaš alat kao spas u zadnji čas, no iznose mi konvertira pogrešno, kao da očekuje drugi format. 

Primjerice,  

€3.500,00 EUR (376,725,00 kn)
€2.800,00 EUR (602,760,00 kn)
€2.500,00 EUR (376,725,00 kn)

Koristim novu sintaksu na kraju theme.liquid datoteke:

```
<script src="https://unpkg.com/@croz/hrk2eur@1.3.1/dist/umd/main.js"></script>
<script>hrk2eur.watchPrices({ autoSwitchOnEurIntroduction: true })</script>
```

Mogu li kako utjecati na format da se ispravno konvertira iznos? 

Lp, 
Mario

**Comment by mblataric** [comment]
Pozdrav, 

Našao sam u Shopify postavkama formatiranje iznosa i maknuo € na početku iznosa. 
Sada radi ispravno. 

Lp, 
Mario

**Comment by jtomic-croz** [comment]
Pozdrav,

problem je kod pokusaja prepoznavanja iznosa. Kod vaseg formata postoji `€` prije iznosa i `EUR` poslije sto zbuni defaultno ponasanje skripte, jer se takav format ne prepoznaje automatski.

U slucaju da ipak zelite takav format, mozete skriptu dodati na malo kompleskniji nacin:

```html
<script src="https://unpkg.com/@croz/hrk2eur@1.3.1/dist/umd/main.js"></script>
<script>hrk2eur.watchPrices({ autoSwitchOnEurIntroduction: true, eurPriceRegexList: [{regex: /(€([0-9.]+,[0-9]{2})\s+EUR)/, priceIndex: 2, decimalSeparator: ',', thousandSeparator: '.'}]  })</script>
```
